export const statements = [
  {
    id: 'ss1',
    type: 'DF',
    category: 'Alimentação',
    description: 'Supermercado',
    expectedValue: 980.0,
    dueDay: 15,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: false },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: false },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: false },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: false },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: false },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: false },
    ],
  },
  {
    id: 'ss2',
    type: 'DV',
    category: 'Fatura Cartão',
    description: 'Fatura Cartão Teste Prime',
    expectedValue: 34.99,
    dueDay: 10,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss3',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Água',
    expectedValue: 120.0,
    dueDay: 25,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss4',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Luz',
    expectedValue: 90.0,
    dueDay: 12,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss5',
    type: 'DV',
    category: 'Serviços',
    description: 'Internet',
    expectedValue: 119.89,
    dueDay: 20,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss6',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss7',
    type: 'DF',
    category: 'Alimentação',
    description: 'Supermercado',
    expectedValue: 980.0,
    dueDay: 15,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: false },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: false },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: false },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: false },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: false },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: false },
    ],
  },
  {
    id: 'ss8',
    type: 'DV',
    category: 'Fatura Cartão',
    description: 'Fatura Cartão Teste Prime',
    expectedValue: 34.99,
    dueDay: 10,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss9',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Água',
    expectedValue: 120.0,
    dueDay: 25,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss10',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Luz',
    expectedValue: 90.0,
    dueDay: 12,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss11',
    type: 'DV',
    category: 'Serviços',
    description: 'Internet',
    expectedValue: 119.89,
    dueDay: 20,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss12',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss13',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss14',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss15',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
];

export const types = [
  { id: 1, label: 'DF', description: 'Despesa Fixa' },
  { id: 2, label: 'DV', description: 'Despesa Variável' },
  { id: 3, label: 'DA', description: 'Despesa Adicional' },
  { id: 4, label: 'RF', description: 'Receita Fixa' },
  { id: 5, label: 'RV', description: 'Receita Variável' },
  { id: 6, label: 'RA', description: 'Receita Adicional' },
];

export const categories = [
  { id: 1, label: 'Alimentação' },
  { id: 2, label: 'Cuidados Pessoais' },
  { id: 3, label: 'Salário' },
  { id: 4, label: 'Aluguel' },
  { id: 5, label: 'Impostos & Taxas' },
  { id: 6, label: 'Transporte' },
  { id: 7, label: 'Educação' },
  { id: 8, label: 'Saúde' },
  { id: 9, label: 'Doações' },
  { id: 10, label: 'Presentes' },
  { id: 11, label: 'Outros' },
];

export const days = (function getDays() {
  const items = [];

  for (let day = 1; day <= 31; day++) {
    items.push(day);
  }
  return items;
})();

export const cards = [
  {
    id: 'cartao1',
    brand: 'Visa',
    name: 'Cartão 1',
    lastNumbers: '0001',
    limit: 1300,
    currentLimit: 1300,
    closingDay: 2,
    dueDay: 10,
    annuity: 155.88,
    fees: 83.88,
    chargeRule: 'always',
    expiryDate: '04/28',
    status: 'Ativo',
  },
  {
    id: 'cartao2',
    brand: 'Visa',
    name: 'Cartão 2',
    lastNumbers: '8789',
    limit: 2480,
    currentLimit: 2480,
    closingDay: 10,
    dueDay: 21,
    annuity: 304.99,
    fees: 0,
    chargeRule: 'always',
    expiryDate: '11/26',
    status: 'Ativo',
  },
  {
    id: 'cartao3',
    brand: 'Mastercard',
    name: 'Cartão 3',
    lastNumbers: '4544',
    limit: 21600,
    currentLimit: 19746.78,
    closingDay: 7,
    dueDay: 16,
    annuity: 809.99,
    fees: 189.88,
    chargeRule: 'always',
    expiryDate: '05/26',
    status: 'Bloqueado',
  },
  {
    id: 'cartao4',
    brand: 'Amex',
    name: 'Cartão Amex Gold',
    lastNumbers: '1115',
    limit: 6800,
    currentLimit: 6800,
    closingDay: 15,
    dueDay: 26,
    annuity: 560,
    fees: 0,
    chargeRule: 'always',
    expiryDate: '05/31',
    status: 'Cancelado',
  },
  {
    id: 'cartao5',
    brand: 'Visa',
    name: 'Cartão 5',
    lastNumbers: '0001',
    limit: 1300,
    currentLimit: 1300,
    closingDay: 2,
    dueDay: 10,
    annuity: 155.88,
    fees: 83.88,
    chargeRule: 'always',
    expiryDate: '04/28',
    status: 'Ativo',
  },
  {
    id: 'cartao6',
    brand: 'Visa',
    name: 'Cartão 6',
    lastNumbers: '8789',
    limit: 2480,
    currentLimit: 2480,
    closingDay: 10,
    dueDay: 21,
    annuity: 304.99,
    fees: 0,
    chargeRule: 'always',
    expiryDate: '11/26',
    status: 'Ativo',
  },
  {
    id: 'cartao7',
    brand: 'Mastercard',
    name: 'Cartão 7',
    lastNumbers: '4544',
    limit: 21600,
    currentLimit: 19746.78,
    closingDay: 7,
    dueDay: 16,
    annuity: 809.99,
    fees: 189.88,
    chargeRule: 'always',
    expiryDate: '05/26',
    status: 'Bloqueado',
  },
  {
    id: 'cartao8',
    brand: 'Amex',
    name: 'Cartão Amex Gold 2',
    lastNumbers: '1115',
    limit: 6800,
    currentLimit: 6800,
    closingDay: 15,
    dueDay: 26,
    annuity: 560,
    fees: 0,
    chargeRule: 'always',
    expiryDate: '05/31',
    status: 'Cancelado',
  },
];

export const cardStatus = [
  { id: 1, label: 'Ativo' },
  { id: 2, label: 'Bloqueado' },
  { id: 3, label: 'Cancelado' },
  { id: 4, label: 'Pendente' },
];

export const brands = [
  { id: 1, label: 'Amex' },
  { id: 2, label: 'Elo' },
  { id: 3, label: 'Mastercard' },
  { id: 4, label: 'Visa' },
  { id: 5, label: 'Outro' },
];

export const chargeRules = [
  { id: 1, value: 'always', label: 'Sempre' },
  { id: 2, value: 'invoice-only', label: 'Se houver fatura' },
  { id: 3, value: 'never', label: 'Nunca' },
];

export const transactionStatus = [
  { id: 1, label: 'Pendente' },
  { id: 2, label: 'Quitado' },
  { id: 3, label: 'Vencido' },
  { id: 4, label: 'Cancelado' },
  { id: 5, label: 'Isento' },
];

export const transactions = [
  {
    id: 't001',
    type: 'DV',
    category: 'Impostos & Taxas',
    description: 'Infração de Trânsito',
    value: 117.89,
    dueDate: '16/06/2023',
    payDate: '16/06/2023',
    installment: 1,
    installments: 1,
    status: 'Pendente',
  },
  {
    id: 't002',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    value: 3489.9,
    dueDate: '06/01/2023',
    payDate: '06/01/2023',
    installment: 1,
    installments: 12,
    status: 'Quitado',
  },
  {
    id: 't003',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    value: 3489.9,
    dueDate: '06/02/2023',
    payDate: '06/02/2023',
    installment: 2,
    installments: 12,
    status: 'Quitado',
  },
];
