export const statements = [
  {
    id: 'ss1',
    type: 'DF',
    category: 'Alimentação',
    description: 'Supermercado',
    expectedValue: 980.0,
    dueDay: 15,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: false },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: false },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: false },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: false },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: false },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: false },
    ],
  },
  {
    id: 'ss2',
    type: 'DV',
    category: 'Fatura Cartão',
    description: 'Fatura Cartão Teste Prime',
    expectedValue: 34.99,
    dueDay: 10,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss3',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Água',
    expectedValue: 120.0,
    dueDay: 25,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss4',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Luz',
    expectedValue: 90.0,
    dueDay: 12,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss5',
    type: 'DV',
    category: 'Serviços',
    description: 'Internet',
    expectedValue: 119.89,
    dueDay: 20,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss6',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss7',
    type: 'DF',
    category: 'Alimentação',
    description: 'Supermercado',
    expectedValue: 980.0,
    dueDay: 15,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: false },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: false },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: false },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: false },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: false },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: false },
    ],
  },
  {
    id: 'ss8',
    type: 'DV',
    category: 'Fatura Cartão',
    description: 'Fatura Cartão Teste Prime',
    expectedValue: 34.99,
    dueDay: 10,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss9',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Água',
    expectedValue: 120.0,
    dueDay: 25,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss10',
    type: 'DV',
    category: 'Moradia',
    description: 'Conta de Luz',
    expectedValue: 90.0,
    dueDay: 12,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss11',
    type: 'DV',
    category: 'Serviços',
    description: 'Internet',
    expectedValue: 119.89,
    dueDay: 20,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss12',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss13',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss14',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
  {
    id: 'ss15',
    type: 'RF',
    category: 'Salário',
    description: 'Meu Salário Mensal',
    expectedValue: 3500,
    dueDay: 6,
    months: [
      { month: '1', label: 'Jan', checked: true },
      { month: '2', label: 'Fev', checked: true },
      { month: '3', label: 'Mar', checked: true },
      { month: '4', label: 'Abr', checked: true },
      { month: '5', label: 'Mai', checked: true },
      { month: '6', label: 'Jun', checked: true },
      { month: '7', label: 'Jul', checked: true },
      { month: '8', label: 'Ago', checked: true },
      { month: '9', label: 'Set', checked: true },
      { month: '10', label: 'Out', checked: true },
      { month: '11', label: 'Nov', checked: true },
      { month: '12', label: 'Dez', checked: true },
    ],
  },
];

export const types = [
  { id: 1, label: 'DF', description: 'Despesa Fixa' },
  { id: 2, label: 'DV', description: 'Despesa Variável' },
  { id: 3, label: 'DA', description: 'Despesa Adicional' },
  { id: 4, label: 'RF', description: 'Receita Fixa' },
  { id: 5, label: 'RV', description: 'Receita Variável' },
  { id: 6, label: 'RA', description: 'Receita Adicional' },
];

export const categories = [
  { id: 1, label: 'Alimentação' },
  { id: 2, label: 'Cuidados Pessoais' },
  { id: 3, label: 'Salário' },
  { id: 4, label: 'Aluguel' },
  { id: 5, label: 'Impostos & Taxas' },
  { id: 6, label: 'Transporte' },
  { id: 7, label: 'Educação' },
  { id: 8, label: 'Saúde' },
  { id: 9, label: 'Doações' },
  { id: 10, label: 'Presentes' },
  { id: 11, label: 'Outros' },
];

export const days = (function getDays() {
  const items = [];

  for (let day = 1; day <= 31; day++) {
    items.push(day);
  }
  return items;
})();
